### PR TITLE
fix sign-in button invisibility

### LINKED ISSUE #517: 🐞 Can not access `sign in` button
- Environment: https://mimirapp.xyz/
- Client: ios 14 / safari

### ✔️ Expected behavior

You should see the button on the screen

### ✖️ Actual behavior

There is only the upper border on the screen

### Screenshot / Descriptions

image

### PR DESCRIPTION
**Pull request by mabrur-h**
close #517 
How it looks in small size displays.
_(The height which was shown on the screenshot was 770px)_ 
image
How it looks in normal displays.
image

### CODE REVIEW

File: packages/frontapp/src/app/pages/StartPage.tsx [hunk 1]
```diff
@@ -27,10 +27,11 @@ const StartPageBackground = styled.div`
   display: flex;
   justify-content: center;
   align-items: flex-end;
-  background-color: #f9faff;
+  background-color: ${colors.light_gray};
   background-image: url('../../assets/bookshelf-pattern.png');
   @media (max-width: ${dimensions.phone_width}) {
     overflow: hidden;
+    align-items: flex-end;
```
Comment (Chichmarin17) [inline packages/frontapp/src/app/pages/StartPage.tsx:34]: Looks like you are dublicating the same property from 29 line

**Review by Chichmarin17 — APPROVED** [review]

**Comment by mabrur-h** [comment]
@sabrina34352 can you review this please?
