### PR TITLE
fix to book card (fix #392)

### LINKED ISSUE #392: Adjust item card to match design
[Figma](https://www.figma.com/file/pxj9Hhk5AdOxXWJP0dq4gT/Library-App-Spec?node-id=4605%3A9469)

image

### PR DESCRIPTION
**Pull request by sabrina34352**
image

### CODE REVIEW

File: packages/frontapp/src/app/components/AllBooksList/index.tsx [hunk 1]
```diff
@@ -38,6 +34,7 @@ const AllBooksList: FC<IAllBooksListProps> = ({ items, sortingCategory }) => {
                 author={item?.author}
                 category={item?.category}
                 date={item?.created_at}
+                status={item?.statuses.slice(-1)[0]}
```
Comment (unrealsolver) [inline packages/frontapp/src/app/components/AllBooksList/index.tsx:37]: How it's possible be undefined here?

File: packages/frontapp/src/app/components/BookCard/index.tsx [hunk 2]
```diff
@@ -85,13 +94,47 @@ const BookCard: FC<IBookCardProps> = ({
...
+        const month = `${getDates(date).returnDate.getMonth() + 1}`.padStart(
+          2,
+          '0'
+        );
+        setStatusText(`Return till: ${day}.${month}`);
+        break;
+      }
+      case 'Prolong': {
+        const day = `${getDates(date).returnDate.getDate()}`.padStart(2, '0');
+        const month = `${getDates(date).returnDate.getMonth() + 1}`.padStart(
```
Comment (unrealsolver) [inline packages/frontapp/src/app/components/BookCard/index.tsx:116]: There are too many repetitive code. Could you please make it more general?

File: packages/frontapp/src/app/components/BookCard/index.tsx [hunk 3]
```diff
@@ -85,13 +94,47 @@ const BookCard: FC<IBookCardProps> = ({
...
+          2,
+          '0'
+        );
+        setStatusText(`Return till: ${day}.${month}`);
```
Comment (unrealsolver) [inline packages/frontapp/src/app/components/BookCard/index.tsx:120]: That's not good approach. It's hard to apply localization with it and reuse formatting. We should use some sort of date formatting library, such as `luxon`, but you could suggest other options.

File: packages/frontapp/src/app/components/BookCard/index.tsx [hunk 4]
```diff
@@ -85,13 +94,47 @@ const BookCard: FC<IBookCardProps> = ({
...
+        break;
+      }
+      case 'Overdue':
+        setStatusText('Overdue');
+        break;
+      default:
+        setStatusText('');
+        break;
+    }
+  }, [currentStatus]);
```
Comment (unrealsolver) [inline packages/frontapp/src/app/components/BookCard/index.tsx:130]: I believe it causes unnecessary renders. This is one way function, so it might be used without `useEffect` and `setStatusText`. Just regular (input) => statusText

**Review by unrealsolver — CHANGES_REQUESTED** [review]

File: packages/frontapp/src/app/components/BookCard/index.tsx (hunk 3 above)
Comment (sabrina34352) [reply packages/frontapp/src/app/components/BookCard/index.tsx]: i added hook that does everything for getting time, i think it replaces the need for luxon

**Review by unrealsolver — APPROVED** [review]
Please add snapshot or component unit test!

File: packages/frontapp/src/app/components/BookCard/index.spec.tsx [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+      t: (str: string | null) => str,
+      i18n: {
+        changeLanguage: () =>
+          new Promise(() => {
+            return;
+          }),
+      },
+    };
+  },
+}));
```
Comment (unrealsolver) [inline packages/frontapp/src/app/components/BookCard/index.spec.tsx:21]: Would be nice to make this reusable or available by default in all tests

File: packages/frontapp/src/app/components/BookCard/index.spec.tsx [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+      t('Statuses.Free')
+    );
+  });
+
+  it('if the picture is not given, use the default one', () => {
+    render(<BookCard />, {
+      wrapper: BrowserRouter,
+    });
+    expect(screen.getByTestId('bookImage')).toHaveAttribute('src', bookImage);
+  });
```
Comment (unrealsolver) [inline packages/frontapp/src/app/components/BookCard/index.spec.tsx:48]: Well, these tests do something, of course. But they cover very little of the behavior. I would recommend use snapshot testing (match whole dom structure with presaved one)

**Review by unrealsolver — APPROVED** [review]
